[project]
name = "cams-biometrics"
version = "0.1.0"
description = "Cams Biometrics Tools"
dependencies = [
    "fastmcp>=0.1.0",
    "httpx>=0.25.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
